import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary-dark relative`}>
        <div className="w-[30vw] h-[30vw] bg-[#77347C] opacity-30 absolute rounded-full top-0 left-0 blur-[120px]	"></div>
        <div className="w-[30vw] h-[30vw] bg-[#30336C] opacity-30 absolute rounded-full top-[20vh] left-[20vw] blur-[120px]	"></div>
        {children}
      </body>
    </html>
  );
}
